### ISSUE TITLE
Scan commands not implemented?

### ISSUE THREAD

**Issue by coleifer** [seppo0010/rlite#14]
Hi, first of all thanks for your awesome work on this project.

I noticed that the `scan` commands are commented out:

https://github.com/seppo0010/rlite/blob/454eaa73427791fe055bec8292bd8d84c70e000c/src/hirlite.c#L4113

Any timeline or plan for implementing these? Are there any alternative commands I should use instead?

**Comment by seppo0010** [comment]
Hi, thanks for the compliment.

I did not do the scan commands, because Redis's implementation relies on some internal structure to return the iteration integer, and I don't have anything similar to it.

If I was going to implemented, it would basically return all matched elements every time, and it'd be just a wrapper around `KEYS`/`SMEMBERS`/`ZRANGE`/`HGETALL`.

**Comment by coleifer** [comment]
Thanks for the explanation!
