### ISSUE TITLE
Feature request: user-defined commands?

### ISSUE THREAD

**Issue by coleifer** [seppo0010/rlite#15]
It would be really cool if the user could define their own `RLite` commands. This is supported by [Vedis](http://vedis.symisc.net), another embedded Redis-like database.

**Comment by seppo0010** [comment]
Doesn't lua scripting address your use case?

**Comment by coleifer** [comment]
Well, if there was a C API (a-la http://vedis.symisc.net/c_api/vedis_register_command.html) then someone could write their own commands in any language. It'd be pretty cool, a tangible perk of having an embedded data-store.

**Comment by seppo0010** [comment]
I'm sorry, but I don't like the idea.

It would add a lot of complexity, it would need more documentation, and require long term commitment to the internal C API, while the benefit is just being able to use any language instead of lua for custom scripts. It would also increment the burden of each language library bindings, to not just register the command but access the C function it might need; at the moment these are a thin layer and they would remain one if possible.

**Comment by coleifer** [comment]
@seppo0010 makes sense, thanks for hearing me out. Keep up the good work!
